using System;
namespace cocos2d.EmbeddableView.OpenTK
{
    /// <summary>
    /// Indicates that this function is generated automatically by a tool.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class AutoGeneratedAttribute : Attribute
    {
        /// <summary>
        /// Specifies the category of this OpenGL function.
        /// </summary>
        public string Category;

        /// <summary>
        /// Specifies the version of this OpenGL function.
        /// </summary>
        public string Version;

        /// <summary>
        /// Specifies the entry point of the OpenGL function.
        /// </summary>
        public string EntryPoint;

        /// <summary>
        /// Constructs a new AutoGeneratedAttribute instance.
        /// </summary>
        public AutoGeneratedAttribute()
        {
        }
    }
}

