dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Android\cocos2d.Android.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Android.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Windows\cocos2d.Windows.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Windows.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.iOS\cocos2d.iOS.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.iOS.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.DesktopGL\cocos2d.DesktopGL.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.DesktopGL.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Linux\cocos2d.Linux.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Linux.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.macOS\cocos2d.macOS.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.macOS.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"

dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.iOS\cocos2d.Core.iOS.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.iOS.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.DesktopGL\cocos2d.Core.DesktopGL.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.DesktopGL.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.Windows\cocos2d.Core.Windows.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.Windows.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.Android\cocos2d.Core.Android.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.Android.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.Linux\cocos2d.Core.Linux.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.Linux.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"
dotnet pack "..\cocos2d-mono\cocos2d\cocos2d.Core.macOS\cocos2d.Core.macOS.csproj" -p:NuspecFile=".\..\..\Nuget Packages\Cocos2D.Core.macOS.nuspec" -c Release -o "..\cocos2d-mono\Nuget Packages"