name: Trigger Docs Site Rebuild

on:
  push:
    branches: [master]

jobs:
  notify-docs-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger cocos2d-mono-docs workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_REPO_PAT }}
          repository: brandmooffin/cocos2d-mono-docs
          event-type: update-docs
          client-payload: '{"source":"brandmooffin/cocos2d-mono", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
